# configuration file for the datasets
# options: ['mut1ny_head_segmentation_pro_v2']

train : 
  mut1ny_head_segmentation_pro_v2 :
    split: train

  mut1ny_head_segmentation_pro_v2 :
    split: val

    
val :
  # lfw-deepfunneled :
  #   split: all

  mut1ny_head_segmentation_pro_v2 :
    split: test 

test :
  lfw:
    split: all


num_seg_classes:
  mut1ny_head_segmentation_pro_v2: 19

num_IDs:
  lfw:  5749
  lfw-deepfunneled: 5749
  mut1ny_head_segmentation_pro_v2: 85
  MS_Celeb_1K : 1000
  MS1M : 85742
  MS_Dig_1M_72: 10000
  MS_Dig_1M_5: 66666